// C:\Users\PC\Desktop\Agricole\filahati\lib\feed-data.ts
// Complete Feed Database with Nutritional Values

import { Feed, AMV } from './calculations';

// Complete list of feeds with their nutritional values
export const defaultFeeds: Feed[] = [
  // ==========================================
  // FORAGES - ENSILAGES
  // ==========================================
  {
    id: '1',
    name: 'Corn Silage',
    nameFr: 'Ensilage de maïs',
    nameAr: 'سيلاج الذرة',
    category: 'forage',
    subCategory: 'silage',
    ms: 35,
    ufl: 0.90,
    ufv: 0.80,
    pdin: 50,
    pdie: 68,
    uel: 1.05,
    ca: 3.5,
    p: 2.5,
    mg: 1.8,
    na: 0.5,
    k: 12,
    cl: 4,
    s: 1.5
  },
  {
    id: '2',
    name: 'Grass Silage',
    nameFr: "Ensilage d'herbe",
    nameAr: 'سيلاج العشب',
    category: 'forage',
    subCategory: 'silage',
    ms: 30,
    ufl: 0.85,
    ufv: 0.75,
    pdin: 85,
    pdie: 75,
    uel: 1.10,
    ca: 6.0,
    p: 3.5,
    mg: 2.5,
    na: 0.8,
    k: 25,
    cl: 5,
    s: 2.0
  },
  {
    id: '2a',
    name: 'Lucerne Silage',
    nameFr: 'Ensilage de luzerne',
    nameAr: 'سيلاج البرسيم',
    category: 'forage',
    subCategory: 'silage',
    ms: 40,
    ufl: 0.75,
    ufv: 0.68,
    pdin: 120,
    pdie: 85,
    uel: 1.15,
    ca: 14.0,
    p: 3.0,
    mg: 3.5,
    na: 1.0,
    k: 28,
    cl: 3.5,
    s: 2.5
  },
  
  // ==========================================
  // FORAGES - HAY (FOIN)
  // ==========================================
  {
    id: '3',
    name: 'Alfalfa Hay',
    nameFr: 'Foin de luzerne',
    nameAr: 'تبن البرسيم',
    category: 'forage',
    subCategory: 'hay',
    ms: 85,
    ufl: 0.67,
    ufv: 0.58,
    pdin: 114,
    pdie: 94,
    uel: 1.04,
    ca: 13.0,
    p: 2.1,
    mg: 3.0,
    na: 0.8,
    k: 22,
    cl: 3.0,
    s: 2.2
  },
  {
    id: '4',
    name: 'Oat Hay',
    nameFr: "Foin d'avoine",
    nameAr: 'تبن الشوفان',
    category: 'forage',
    subCategory: 'hay',
    ms: 88,
    ufl: 0.65,
    ufv: 0.55,
    pdin: 40,
    pdie: 59,
    uel: 1.75,
    ca: 3.0,
    p: 2.5,
    mg: 1.5,
    na: 0.5,
    k: 18,
    cl: 3.5,
    s: 1.8
  },
  {
    id: '5',
    name: 'Vetch-Oat Hay',
    nameFr: 'Foin de vesce-avoine',
    nameAr: 'تبن البيقية والشوفان',
    category: 'forage',
    subCategory: 'hay',
    ms: 88,
    ufl: 0.70,
    ufv: 0.60,
    pdin: 75,
    pdie: 70,
    uel: 1.20,
    ca: 8.0,
    p: 2.8,
    mg: 2.2,
    na: 0.6,
    k: 20,
    cl: 3.2,
    s: 2.0
  },
  {
    id: '5a',
    name: 'Ryegrass Hay',
    nameFr: "Foin de ray-grass",
    nameAr: 'تبن الريجراس',
    category: 'forage',
    subCategory: 'hay',
    ms: 86,
    ufl: 0.72,
    ufv: 0.62,
    pdin: 68,
    pdie: 72,
    uel: 1.18,
    ca: 5.5,
    p: 3.0,
    mg: 2.0,
    na: 0.7,
    k: 24,
    cl: 4.0,
    s: 2.0
  },
  
  // ==========================================
  // FORAGES - STRAW (PAILLE)
  // ==========================================
  {
    id: '6',
    name: 'Wheat Straw',
    nameFr: 'Paille de blé',
    nameAr: 'قش القمح',
    category: 'forage',
    subCategory: 'straw',
    ms: 88,
    ufl: 0.42,
    ufv: 0.31,
    pdin: 22,
    pdie: 44,
    uel: 2.0,
    ca: 2.0,
    p: 1.0,
    mg: 1.0,
    na: 0.3,
    k: 15,
    cl: 2.5,
    s: 1.2
  },
  {
    id: '6a',
    name: 'Barley Straw',
    nameFr: 'Paille d\'orge',
    nameAr: 'قش الشعير',
    category: 'forage',
    subCategory: 'straw',
    ms: 87,
    ufl: 0.38,
    ufv: 0.28,
    pdin: 20,
    pdie: 40,
    uel: 2.1,
    ca: 2.5,
    p: 0.8,
    mg: 1.2,
    na: 0.3,
    k: 18,
    cl: 3.0,
    s: 1.0
  },
  
  // ==========================================
  // FORAGES - FRESH (VERT)
  // ==========================================
  {
    id: '7',
    name: 'Fresh Berseem',
    nameFr: 'Bersim vert',
    nameAr: 'برسيم أخضر',
    category: 'forage',
    subCategory: 'fresh',
    ms: 11.1,
    ufl: 0.79,
    ufv: 0.73,
    pdin: 140,
    pdie: 124,
    uel: 0.85,
    ca: 15.0,
    p: 3.5,
    mg: 3.5,
    na: 1.2,
    k: 30,
    cl: 4.5,
    s: 2.5
  },
  {
    id: '7a',
    name: 'Fresh Ryegrass',
    nameFr: 'Ray-grass vert',
    nameAr: 'ريجراس أخضر',
    category: 'forage',
    subCategory: 'fresh',
    ms: 16,
    ufl: 0.92,
    ufv: 0.88,
    pdin: 110,
    pdie: 105,
    uel: 0.95,
    ca: 5.5,
    p: 3.8,
    mg: 2.5,
    na: 1.0,
    k: 28,
    cl: 5.0,
    s: 2.2
  },
  
  // ==========================================
  // ENERGY CONCENTRATES
  // ==========================================
  {
    id: '8',
    name: 'Corn Grain',
    nameFr: 'Maïs grain',
    nameAr: 'حبوب الذرة',
    category: 'concentrate',
    subCategory: 'energy',
    ms: 86,
    ufl: 1.10,
    ufv: 1.12,
    pdin: 71,
    pdie: 103,
    uel: 0,
    ca: 0.3,
    p: 2.2,
    mg: 1.0,
    na: 0.1,
    k: 3.5,
    cl: 0.5,
    s: 1.0
  },
  {
    id: '9',
    name: 'Barley Grain',
    nameFr: 'Orge grain',
    nameAr: 'حبوب الشعير',
    category: 'concentrate',
    subCategory: 'energy',
    ms: 86,
    ufl: 1.00,
    ufv: 1.00,
    pdin: 78,
    pdie: 94,
    uel: 0,
    ca: 0.5,
    p: 3.5,
    mg: 1.2,
    na: 0.1,
    k: 4.5,
    cl: 0.6,
    s: 1.2
  },
  {
    id: '10',
    name: 'Wheat Bran',
    nameFr: 'Son de blé',
    nameAr: 'نخالة القمح',
    category: 'concentrate',
    subCategory: 'energy',
    ms: 87,
    ufl: 0.73,
    ufv: 0.67,
    pdin: 92,
    pdie: 74,
    uel: 0,
    ca: 1.4,
    p: 12.2,
    mg: 5.0,
    na: 0.5,
    k: 12,
    cl: 1.5,
    s: 1.8
  },
  {
    id: '11',
    name: 'Dry Beet Pulp',
    nameFr: 'Pulpe sèche de betterave',
    nameAr: 'لب البنجر الجاف',
    category: 'concentrate',
    subCategory: 'energy',
    ms: 90,
    ufl: 0.90,
    ufv: 0.88,
    pdin: 56,
    pdie: 94,
    uel: 0,
    ca: 13.0,
    p: 1.0,
    mg: 2.5,
    na: 0.3,
    k: 2.5,
    cl: 0.5,
    s: 1.0
  },
  {
    id: '11a',
    name: 'Molasses',
    nameFr: 'Mélasse',
    nameAr: 'دبس السكر',
    category: 'concentrate',
    subCategory: 'energy',
    ms: 75,
    ufl: 0.85,
    ufv: 0.82,
    pdin: 45,
    pdie: 72,
    uel: 0,
    ca: 8.0,
    p: 0.8,
    mg: 2.0,
    na: 0.5,
    k: 35,
    cl: 3.0,
    s: 1.5
  },
  
  // ==========================================
  // PROTEIN CONCENTRATES (TOURTEAUX)
  // ==========================================
  {
    id: '12',
    name: 'Soybean Meal 44',
    nameFr: 'Tourteau de soja 44',
    nameAr: 'كسب فول الصويا 44',
    category: 'concentrate',
    subCategory: 'protein',
    ms: 87.2,
    ufl: 0.99,
    ufv: 0.98,
    pdin: 303,
    pdie: 210,
    uel: 0,
    ca: 3.0,
    p: 6.1,
    mg: 3.0,
    na: 0.3,
    k: 20,
    cl: 0.5,
    s: 3.0
  },
  {
    id: '13',
    name: 'Soybean Meal 48',
    nameFr: 'Tourteau de soja 48',
    nameAr: 'كسب فول الصويا 48',
    category: 'concentrate',
    subCategory: 'protein',
    ms: 87.5,
    ufl: 1.05,
    ufv: 1.03,
    pdin: 343,
    pdie: 234,
    uel: 0,
    ca: 3.2,
    p: 6.5,
    mg: 3.2,
    na: 0.3,
    k: 21,
    cl: 0.5,
    s: 3.2
  },
  {
    id: '14',
    name: 'Sunflower Meal',
    nameFr: 'Tourteau de tournesol',
    nameAr: 'كسب دوار الشمس',
    category: 'concentrate',
    subCategory: 'protein',
    ms: 89,
    ufl: 0.65,
    ufv: 0.56,
    pdin: 219,
    pdie: 115,
    uel: 0,
    ca: 3.5,
    p: 10.0,
    mg: 5.0,
    na: 0.4,
    k: 15,
    cl: 1.0,
    s: 2.5
  },
  {
    id: '15',
    name: 'Rapeseed Meal',
    nameFr: 'Tourteau de colza',
    nameAr: 'كسب الكولزا',
    category: 'concentrate',
    subCategory: 'protein',
    ms: 88,
    ufl: 0.85,
    ufv: 0.78,
    pdin: 231,
    pdie: 149,
    uel: 0,
    ca: 7.5,
    p: 11.5,
    mg: 4.5,
    na: 0.5,
    k: 13,
    cl: 1.2,
    s: 3.0
  },
  {
    id: '15a',
    name: 'Cottonseed Meal',
    nameFr: 'Tourteau de coton',
    nameAr: 'كسب القطن',
    category: 'concentrate',
    subCategory: 'protein',
    ms: 90,
    ufl: 0.78,
    ufv: 0.72,
    pdin: 250,
    pdie: 160,
    uel: 0,
    ca: 2.5,
    p: 11.0,
    mg: 4.0,
    na: 0.3,
    k: 16,
    cl: 1.0,
    s: 2.8
  },
  {
    id: '15b',
    name: 'Peanut Meal',
    nameFr: 'Tourteau d\'arachide',
    nameAr: 'كسب الفول السوداني',
    category: 'concentrate',
    subCategory: 'protein',
    ms: 90,
    ufl: 0.88,
    ufv: 0.82,
    pdin: 280,
    pdie: 185,
    uel: 0,
    ca: 3.0,
    p: 6.0,
    mg: 3.5,
    na: 0.3,
    k: 14,
    cl: 0.8,
    s: 2.5
  },
  
  // ==========================================
  // COMPOUND FEEDS (CONCENTRÉS VL)
  // ==========================================
  {
    id: '16',
    name: 'Dairy Concentrate VL',
    nameFr: 'Concentré VL 1/2kg de lait',
    nameAr: 'علف مركز VL',
    category: 'concentrate',
    subCategory: 'compound',
    ms: 90,
    ufl: 0.98,
    ufv: 0.95,
    pdin: 107,
    pdie: 106,
    uel: 0,
    ca: 10.0,
    p: 6.0,
    mg: 3.5,
    na: 2.0,
    k: 10,
    cl: 2.5,
    s: 2.0
  },
  {
    id: '16a',
    name: 'High Yield Concentrate',
    nameFr: 'Concentré Haute Production',
    nameAr: 'علف مركز إنتاج عالي',
    category: 'concentrate',
    subCategory: 'compound',
    ms: 88,
    ufl: 1.05,
    ufv: 1.02,
    pdin: 140,
    pdie: 130,
    uel: 0,
    ca: 12.0,
    p: 7.0,
    mg: 4.0,
    na: 2.5,
    k: 12,
    cl: 3.0,
    s: 2.2
  },
  
  // ==========================================
  // MINERALS AND ADDITIVES
  // ==========================================
  {
    id: '17',
    name: 'Calcium Carbonate',
    nameFr: 'Carbonate de calcium (CaCO3)',
    nameAr: 'كربونات الكالسيوم',
    category: 'mineral',
    subCategory: 'calcium',
    ms: 100,
    ufl: 0,
    pdin: 0,
    pdie: 0,
    uel: 0,
    ca: 400,
    p: 0,
    mg: 0,
    na: 0,
    k: 0,
    cl: 0,
    s: 0
  },
  {
    id: '18',
    name: 'Dicalcium Phosphate',
    nameFr: 'Phosphate bicalcique',
    nameAr: 'فوسفات ثنائي الكالسيوم',
    category: 'mineral',
    subCategory: 'phosphorus',
    ms: 100,
    ufl: 0,
    pdin: 0,
    pdie: 0,
    uel: 0,
    ca: 260,
    p: 180,
    mg: 0,
    na: 0,
    k: 0,
    cl: 0,
    s: 0
  },
  {
    id: '19',
    name: 'Sodium Bicarbonate',
    nameFr: 'Bicarbonate de sodium',
    nameAr: 'بيكربونات الصوديوم',
    category: 'mineral',
    subCategory: 'buffer',
    ms: 100,
    ufl: 0,
    pdin: 0,
    pdie: 0,
    uel: 0,
    ca: 0,
    p: 0,
    mg: 0,
    na: 270,
    k: 0,
    cl: 0,
    s: 0
  },
  {
    id: '20',
    name: 'Magnesium Oxide',
    nameFr: 'Oxyde de magnésium',
    nameAr: 'أكسيد المغنيسيوم',
    category: 'mineral',
    subCategory: 'magnesium',
    ms: 100,
    ufl: 0,
    pdin: 0,
    pdie: 0,
    uel: 0,
    ca: 0,
    p: 0,
    mg: 600,
    na: 0,
    k: 0,
    cl: 0,
    s: 0
  },
  {
    id: '21',
    name: 'Propylene Glycol',
    nameFr: 'Propylène Glycol (Propaline)',
    nameAr: 'بروبيلين جليكول',
    category: 'mineral',
    subCategory: 'additive',
    ms: 100,
    ufl: 0,
    pdin: 0,
    pdie: 0,
    uel: 0,
    ca: 0,
    p: 0,
    mg: 0,
    na: 0,
    k: 0,
    cl: 0,
    s: 0
  }
];

// Export AMV options
export const amvOptions = [
  { id: 'amv1', name: '5/25', nameFr: 'AMV 5/25', nameAr: 'AMV 5/25', caPercent: 25, pPercent: 5, mgPercent: 3, naPercent: 5, ratio: 5 },
  { id: 'amv2', name: '5/20', nameFr: 'AMV 5/20', nameAr: 'AMV 5/20', caPercent: 20, pPercent: 5, mgPercent: 3, naPercent: 5, ratio: 4 },
  { id: 'amv3', name: '7/21', nameFr: 'AMV 7/21', nameAr: 'AMV 7/21', caPercent: 21, pPercent: 7, mgPercent: 4, naPercent: 6, ratio: 3 },
  { id: 'amv4', name: '8/16', nameFr: 'AMV 8/16', nameAr: 'AMV 8/16', caPercent: 16, pPercent: 8, mgPercent: 4, naPercent: 6, ratio: 2 },
  { id: 'amv5', name: '10/20', nameFr: 'AMV 10/20', nameAr: 'AMV 10/20', caPercent: 20, pPercent: 10, mgPercent: 3, naPercent: 5, ratio: 2 },
  { id: 'amv6', name: '12/22', nameFr: 'AMV 12/22', nameAr: 'AMV 12/22', caPercent: 22, pPercent: 12, mgPercent: 4, naPercent: 6, ratio: 1.83 },
  { id: 'amv7', name: '8/12', nameFr: 'AMV 8/12', nameAr: 'AMV 8/12', caPercent: 12, pPercent: 8, mgPercent: 5, naPercent: 7, ratio: 1.5 },
  { id: 'amv8', name: '10/10', nameFr: 'AMV 10/10', nameAr: 'AMV 10/10', caPercent: 10, pPercent: 10, mgPercent: 5, naPercent: 7, ratio: 1 },
  { id: 'amv9', name: '12/12', nameFr: 'AMV 12/12', nameAr: 'AMV 12/12', caPercent: 12, pPercent: 12, mgPercent: 4, naPercent: 6, ratio: 1 },
  { id: 'amv10', name: '16/16', nameFr: 'AMV 16/16', nameAr: 'AMV 16/16', caPercent: 16, pPercent: 16, mgPercent: 3, naPercent: 5, ratio: 1 },
  { id: 'amv11', name: '12/8', nameFr: 'AMV 12/8', nameAr: 'AMV 12/8', caPercent: 8, pPercent: 12, mgPercent: 5, naPercent: 7, ratio: 0.67 },
  { id: 'amv12', name: '20/15', nameFr: 'AMV 20/15', nameAr: 'AMV 20/15', caPercent: 15, pPercent: 20, mgPercent: 3, naPercent: 5, ratio: 0.75 }
];

export function selectAMV(caDeficit: number, pDeficit: number) {
  if (pDeficit <= 0) return null;
  const ratio = caDeficit / pDeficit;
  
  if (ratio > 3) return amvOptions.find(amv => amv.ratio >= 3) || amvOptions[0];
  if (ratio >= 2) return amvOptions.find(amv => amv.ratio >= 2 && amv.ratio < 3) || amvOptions[3];
  if (ratio >= 1.5) return amvOptions.find(amv => amv.ratio >= 1.5 && amv.ratio < 2) || amvOptions[6];
  if (ratio >= 1) return amvOptions.find(amv => amv.ratio === 1) || amvOptions[7];
  if (ratio >= 0.75) return amvOptions.find(amv => amv.ratio < 1 && amv.ratio >= 0.75) || amvOptions[11];
  return amvOptions.find(amv => amv.ratio < 0.75) || amvOptions[10];
}